environment:
  dataset_path: ./data/examples/training_dataset.pkl  # Path to the dataset, can be a pickle or csv file
  seed: 42
  chromosome_HEAD_len: 10
  # Cache configuration
  cache_enabled: true
  cache_capacity: 20000
  cache_type: lru  # lru or clock

agent:
  # Saving the results
  save_dir: ./
  save_start: 0
  save_frequency: 500

  # Simulation parameters
  action_cap: null  # After action_cap actions, start_state is seen again.
  random_seed: 42

  # RL parameters
  num_trials: 1000
  episodes_trial: 1  # The initial state is visited num_episodes times
  gamma: 0.99  # Discount factor: close to 1 values future states highly, close to 0 values immediate states in path more
  continuous_deadloop: 2  # Performes n repetitive actions. Note that the deadloop is detected only after NN_sleep.
  latent_deadloop: 4  # Performes n invalid actions for the same state (should be more than continuous_deadloop+1 to make sense)
  invalid_terminals: false  # if True, the invalid actions will be considered as terminal states

  # Dynamic variable
  initial_epsilon: 1.0  # Larger epsilon means more random selection (exploration)
  epsilon_min: 0.1  # Smallest epsilon value
  epsilon_decay: 0.99968  # Decay rate for epsilon
  start_decay: 10  # the start trial to decay the epsilon
  # Option to add Bayesian inference in reward calculation
  bayesian: false  # If True, the analysis of the posterior distribution added as a bonus to the reward formulation

  # NN hyperparameters
  learning_rate: 0.0005  # for optimization of the NN
  batch_size: 150  # training size for the main network
  train_frequency: 5  # train the main model every `train_frequency` steps
  update_target_frequency: 1000  # Frequency to update target network
  NN_sleep: 1000  # The number of initial data that should be gathered before the first training (should be larger than batch_size)
  buffer_capacity: 15000
  optimizer_type: adam  # or pass optimizer object directly

  # Prioritized replay parameters
  prioritized_replay_alpha: 0.6
  prioritized_replay_eps: 1.0E-6
  initial_beta: 0.4  # The larger the beta, the lower weights we multiply to the loss
  beta_jump: 1.06
  start_jump: null  # Or start when mean_loss < 1. If null, computed as (2/5) * num_trials
  anneal_fraction: null  # If null, computed as (3/5 * num_trials) / num_trials - 0.005
  final_beta: 0.7
